"""Add email verification and restricted access configuration

Revision ID: 00356a817c87
Revises: 
Create Date: 2026-01-05 12:55:39.731355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00356a817c87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acumulado_anual',
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('tipo_planilla_id', sa.String(length=26), nullable=False),
    sa.Column('empresa_id', sa.String(length=26), nullable=False),
    sa.Column('periodo_fiscal_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fiscal_fin', sa.Date(), nullable=False),
    sa.Column('salario_bruto_acumulado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('salario_gravable_acumulado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deducciones_antes_impuesto_acumulado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('impuesto_retenido_acumulado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('periodos_procesados', sa.Integer(), nullable=False),
    sa.Column('ultimo_periodo_procesado', sa.Date(), nullable=True),
    sa.Column('salario_acumulado_mes', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('mes_actual', sa.Integer(), nullable=True),
    sa.Column('datos_adicionales', coati_payroll.model.OrjsonType(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['tipo_planilla_id'], ['tipo_planilla.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id', 'tipo_planilla_id', 'empresa_id', 'periodo_fiscal_inicio', name='uq_acumulado_empleado_tipo_empresa_periodo')
    )
    with op.batch_alter_table('acumulado_anual', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acumulado_anual_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acumulado_anual_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acumulado_anual_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acumulado_anual_periodo_fiscal_inicio'), ['periodo_fiscal_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_acumulado_anual_tipo_planilla_id'), ['tipo_planilla_id'], unique=False)

    op.create_table('adelanto',
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('deduccion_id', sa.String(length=26), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha_solicitud', sa.Date(), nullable=False),
    sa.Column('fecha_aprobacion', sa.Date(), nullable=True),
    sa.Column('fecha_desembolso', sa.Date(), nullable=True),
    sa.Column('monto_solicitado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_aprobado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('saldo_pendiente', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda_id', sa.String(length=26), nullable=True),
    sa.Column('monto_deducido_moneda_planilla', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monto_aplicado_moneda_prestamo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cuotas_pactadas', sa.Integer(), nullable=True),
    sa.Column('monto_por_cuota', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tasa_interes', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('tipo_interes', sa.String(length=20), nullable=True),
    sa.Column('metodo_amortizacion', sa.String(length=20), nullable=True),
    sa.Column('interes_acumulado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_ultimo_calculo_interes', sa.Date(), nullable=True),
    sa.Column('cuenta_debe', sa.String(length=64), nullable=True),
    sa.Column('descripcion_cuenta_debe', sa.String(length=255), nullable=True),
    sa.Column('cuenta_haber', sa.String(length=64), nullable=True),
    sa.Column('descripcion_cuenta_haber', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('aprobado_por', sa.String(length=150), nullable=True),
    sa.Column('rechazado_por', sa.String(length=150), nullable=True),
    sa.Column('motivo_rechazo', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['deduccion_id'], ['deduccion.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['moneda_id'], ['moneda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adelanto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adelanto_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adelanto_id'), ['id'], unique=False)

    op.create_table('carga_inicial_prestacion',
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('prestacion_id', sa.String(length=26), nullable=False),
    sa.Column('anio_corte', sa.Integer(), nullable=False),
    sa.Column('mes_corte', sa.Integer(), nullable=False),
    sa.Column('moneda_id', sa.String(length=26), nullable=False),
    sa.Column('saldo_acumulado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('saldo_convertido', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_aplicacion', sa.DateTime(), nullable=True),
    sa.Column('aplicado_por', sa.String(length=150), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['moneda_id'], ['moneda.id'], ),
    sa.ForeignKeyConstraint(['prestacion_id'], ['prestacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id', 'prestacion_id', 'anio_corte', 'mes_corte', name='uq_carga_inicial_emp_prest_periodo')
    )
    with op.batch_alter_table('carga_inicial_prestacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carga_inicial_prestacion_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carga_inicial_prestacion_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carga_inicial_prestacion_prestacion_id'), ['prestacion_id'], unique=False)

    op.create_table('historial_salario',
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('fecha_efectiva', sa.Date(), nullable=False),
    sa.Column('salario_anterior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('salario_nuevo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('autorizado_por', sa.String(length=150), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial_salario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_salario_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_salario_fecha_efectiva'), ['fecha_efectiva'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_salario_id'), ['id'], unique=False)

    op.create_table('planilla_audit_log',
    sa.Column('planilla_id', sa.String(length=26), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('cambios', coati_payroll.model.OrjsonType(), nullable=True),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['planilla_id'], ['planilla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planilla_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planilla_audit_log_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_planilla_audit_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planilla_audit_log_usuario'), ['usuario'], unique=False)

    op.create_table('regla_calculo_audit_log',
    sa.Column('regla_calculo_id', sa.String(length=26), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('cambios', coati_payroll.model.OrjsonType(), nullable=True),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['regla_calculo_id'], ['regla_calculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regla_calculo_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regla_calculo_audit_log_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_regla_calculo_audit_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regla_calculo_audit_log_usuario'), ['usuario'], unique=False)

    op.create_table('vacacion_descansada',
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias_tomados', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('autorizado_por', sa.String(length=150), nullable=True),
    sa.Column('fecha_autorizacion', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacacion_descansada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacacion_descansada_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacacion_descansada_id'), ['id'], unique=False)

    op.create_table('vacacion_empleado',
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('configuracion_id', sa.String(length=26), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('dias_devengados', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dias_tomados', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dias_pendientes', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dias_pagados', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_ultimo_calculo', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['configuracion_id'], ['configuracion_vacaciones.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id', 'anio', name='uq_vacacion_empleado_anio')
    )
    with op.batch_alter_table('vacacion_empleado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacacion_empleado_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacacion_empleado_id'), ['id'], unique=False)

    op.create_table('vacation_policy',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('planilla_id', sa.String(length=26), nullable=True),
    sa.Column('empresa_id', sa.String(length=26), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('accrual_method', sa.String(length=20), nullable=False),
    sa.Column('accrual_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('accrual_frequency', sa.String(length=20), nullable=False),
    sa.Column('accrual_basis', sa.String(length=20), nullable=True),
    sa.Column('min_service_days', sa.Integer(), nullable=False),
    sa.Column('seniority_tiers', sa.JSON(), nullable=True),
    sa.Column('max_balance', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('carryover_limit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('allow_negative', sa.Boolean(), nullable=False),
    sa.Column('expiration_rule', sa.String(length=20), nullable=False),
    sa.Column('expiration_months', sa.Integer(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('payout_on_termination', sa.Boolean(), nullable=False),
    sa.Column('unit_type', sa.String(length=10), nullable=False),
    sa.Column('count_weekends', sa.Boolean(), nullable=False),
    sa.Column('count_holidays', sa.Boolean(), nullable=False),
    sa.Column('partial_units_allowed', sa.Boolean(), nullable=False),
    sa.Column('rounding_rule', sa.String(length=10), nullable=True),
    sa.Column('accrue_during_leave', sa.Boolean(), nullable=False),
    sa.Column('configuracion_adicional', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['planilla_id'], ['planilla.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_vacation_policy_codigo')
    )
    with op.batch_alter_table('vacation_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacation_policy_codigo'), ['codigo'], unique=True)
        batch_op.create_index('ix_vacation_policy_empresa', ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacation_policy_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacation_policy_id'), ['id'], unique=False)
        batch_op.create_index('ix_vacation_policy_planilla', ['planilla_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacation_policy_planilla_id'), ['planilla_id'], unique=False)

    op.create_table('adelanto_abono',
    sa.Column('adelanto_id', sa.String(length=26), nullable=False),
    sa.Column('nomina_id', sa.String(length=26), nullable=True),
    sa.Column('liquidacion_id', sa.String(length=26), nullable=True),
    sa.Column('fecha_abono', sa.Date(), nullable=False),
    sa.Column('monto_abonado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_anterior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_posterior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tipo_abono', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('tipo_comprobante', sa.String(length=50), nullable=True),
    sa.Column('numero_comprobante', sa.String(length=100), nullable=True),
    sa.Column('referencia_bancaria', sa.String(length=100), nullable=True),
    sa.Column('cuenta_debe', sa.String(length=64), nullable=True),
    sa.Column('descripcion_cuenta_debe', sa.String(length=255), nullable=True),
    sa.Column('cuenta_haber', sa.String(length=64), nullable=True),
    sa.Column('descripcion_cuenta_haber', sa.String(length=255), nullable=True),
    sa.Column('autorizado_por', sa.String(length=150), nullable=True),
    sa.Column('documento_soporte', sa.String(length=50), nullable=True),
    sa.Column('referencia_documento', sa.String(length=200), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['adelanto_id'], ['adelanto.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidacion.id'], ),
    sa.ForeignKeyConstraint(['nomina_id'], ['nomina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adelanto_abono', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adelanto_abono_adelanto_id'), ['adelanto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adelanto_abono_id'), ['id'], unique=False)

    op.create_table('comprobante_contable',
    sa.Column('nomina_id', sa.String(length=26), nullable=False),
    sa.Column('fecha_calculo', sa.Date(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=True),
    sa.Column('moneda_id', sa.String(length=26), nullable=True),
    sa.Column('total_debitos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_creditos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('advertencias', sa.JSON(), nullable=True),
    sa.Column('aplicado_por', sa.String(length=150), nullable=True),
    sa.Column('fecha_aplicacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('veces_modificado', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moneda_id'], ['moneda.id'], ),
    sa.ForeignKeyConstraint(['nomina_id'], ['nomina.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomina_id')
    )
    with op.batch_alter_table('comprobante_contable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprobante_contable_id'), ['id'], unique=False)

    op.create_table('interes_adelanto',
    sa.Column('adelanto_id', sa.String(length=26), nullable=False),
    sa.Column('nomina_id', sa.String(length=26), nullable=True),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('dias_transcurridos', sa.Integer(), nullable=False),
    sa.Column('saldo_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tasa_aplicada', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('interes_calculado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_anterior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_posterior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['adelanto_id'], ['adelanto.id'], ),
    sa.ForeignKeyConstraint(['nomina_id'], ['nomina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interes_adelanto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interes_adelanto_adelanto_id'), ['adelanto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interes_adelanto_id'), ['id'], unique=False)

    op.create_table('liquidacion_detalle',
    sa.Column('liquidacion_id', sa.String(length=26), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('percepcion_id', sa.String(length=26), nullable=True),
    sa.Column('deduccion_id', sa.String(length=26), nullable=True),
    sa.Column('prestacion_id', sa.String(length=26), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['deduccion_id'], ['deduccion.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidacion.id'], ),
    sa.ForeignKeyConstraint(['percepcion_id'], ['percepcion.id'], ),
    sa.ForeignKeyConstraint(['prestacion_id'], ['prestacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liquidacion_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liquidacion_detalle_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidacion_detalle_liquidacion_id'), ['liquidacion_id'], unique=False)

    op.create_table('nomina_audit_log',
    sa.Column('nomina_id', sa.String(length=26), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('cambios', coati_payroll.model.OrjsonType(), nullable=True),
    sa.Column('estado_anterior', sa.String(length=30), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=30), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['nomina_id'], ['nomina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nomina_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nomina_audit_log_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_nomina_audit_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nomina_audit_log_usuario'), ['usuario'], unique=False)

    op.create_table('nomina_empleado',
    sa.Column('nomina_id', sa.String(length=26), nullable=False),
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('salario_bruto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_ingresos', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_deducciones', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salario_neto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('moneda_origen_id', sa.String(length=26), nullable=True),
    sa.Column('tipo_cambio_aplicado', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('cargo_snapshot', sa.String(length=150), nullable=True),
    sa.Column('area_snapshot', sa.String(length=150), nullable=True),
    sa.Column('centro_costos_snapshot', sa.String(length=150), nullable=True),
    sa.Column('sueldo_base_historico', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['moneda_origen_id'], ['moneda.id'], ),
    sa.ForeignKeyConstraint(['nomina_id'], ['nomina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nomina_empleado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nomina_empleado_id'), ['id'], unique=False)

    op.create_table('prestacion_acumulada',
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('prestacion_id', sa.String(length=26), nullable=False),
    sa.Column('fecha_transaccion', sa.Date(), nullable=False),
    sa.Column('tipo_transaccion', sa.String(length=20), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('moneda_id', sa.String(length=26), nullable=False),
    sa.Column('monto_transaccion', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_anterior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_nuevo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('nomina_id', sa.String(length=26), nullable=True),
    sa.Column('carga_inicial_id', sa.String(length=26), nullable=True),
    sa.Column('empresa_id', sa.String(length=26), nullable=True),
    sa.Column('transaccion_reversada_id', sa.String(length=26), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('procesado_por', sa.String(length=150), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['carga_inicial_id'], ['carga_inicial_prestacion.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['moneda_id'], ['moneda.id'], ),
    sa.ForeignKeyConstraint(['nomina_id'], ['nomina.id'], ),
    sa.ForeignKeyConstraint(['prestacion_id'], ['prestacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prestacion_acumulada', schema=None) as batch_op:
        batch_op.create_index('ix_prestacion_acum_empleado_prestacion', ['empleado_id', 'prestacion_id'], unique=False)
        batch_op.create_index('ix_prestacion_acum_fecha', ['fecha_transaccion'], unique=False)
        batch_op.create_index('ix_prestacion_acum_periodo', ['anio', 'mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_prestacion_acumulada_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_prestacion_acumulada_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prestacion_acumulada_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prestacion_acumulada_fecha_transaccion'), ['fecha_transaccion'], unique=False)
        batch_op.create_index(batch_op.f('ix_prestacion_acumulada_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prestacion_acumulada_prestacion_id'), ['prestacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prestacion_acumulada_tipo_transaccion'), ['tipo_transaccion'], unique=False)

    op.create_table('vacation_account',
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('policy_id', sa.String(length=26), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('last_accrual_date', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['vacation_policy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id', 'policy_id', name='uq_vacation_account_emp_policy')
    )
    with op.batch_alter_table('vacation_account', schema=None) as batch_op:
        batch_op.create_index('ix_vacation_account_empleado', ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacation_account_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacation_account_id'), ['id'], unique=False)
        batch_op.create_index('ix_vacation_account_policy', ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacation_account_policy_id'), ['policy_id'], unique=False)

    op.create_table('comprobante_contable_linea',
    sa.Column('comprobante_id', sa.String(length=26), nullable=False),
    sa.Column('nomina_empleado_id', sa.String(length=26), nullable=False),
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('empleado_codigo', sa.String(length=20), nullable=False),
    sa.Column('empleado_nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo_cuenta', sa.String(length=64), nullable=True),
    sa.Column('descripcion_cuenta', sa.String(length=255), nullable=True),
    sa.Column('centro_costos', sa.String(length=150), nullable=True),
    sa.Column('tipo_debito_credito', sa.String(length=10), nullable=False),
    sa.Column('debito', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credito', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_calculado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('tipo_concepto', sa.String(length=20), nullable=False),
    sa.Column('concepto_codigo', sa.String(length=50), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobante_contable.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['nomina_empleado_id'], ['nomina_empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comprobante_contable_linea', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprobante_contable_linea_centro_costos'), ['centro_costos'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobante_contable_linea_codigo_cuenta'), ['codigo_cuenta'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobante_contable_linea_comprobante_id'), ['comprobante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobante_contable_linea_concepto_codigo'), ['concepto_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobante_contable_linea_empleado_codigo'), ['empleado_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobante_contable_linea_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobante_contable_linea_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobante_contable_linea_nomina_empleado_id'), ['nomina_empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobante_contable_linea_orden'), ['orden'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobante_contable_linea_tipo_concepto'), ['tipo_concepto'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobante_contable_linea_tipo_debito_credito'), ['tipo_debito_credito'], unique=False)

    op.create_table('nomina_detalle',
    sa.Column('nomina_empleado_id', sa.String(length=26), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('percepcion_id', sa.String(length=26), nullable=True),
    sa.Column('deduccion_id', sa.String(length=26), nullable=True),
    sa.Column('prestacion_id', sa.String(length=26), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['deduccion_id'], ['deduccion.id'], ),
    sa.ForeignKeyConstraint(['nomina_empleado_id'], ['nomina_empleado.id'], ),
    sa.ForeignKeyConstraint(['percepcion_id'], ['percepcion.id'], ),
    sa.ForeignKeyConstraint(['prestacion_id'], ['prestacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nomina_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nomina_detalle_id'), ['id'], unique=False)

    op.create_table('vacation_ledger',
    sa.Column('account_id', sa.String(length=26), nullable=False),
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=26), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['vacation_account.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacation_ledger', schema=None) as batch_op:
        batch_op.create_index('ix_vacation_ledger_account', ['account_id'], unique=False)
        batch_op.create_index('ix_vacation_ledger_empleado', ['empleado_id'], unique=False)
        batch_op.create_index('ix_vacation_ledger_fecha', ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacation_ledger_id'), ['id'], unique=False)
        batch_op.create_index('ix_vacation_ledger_type', ['entry_type'], unique=False)

    op.create_table('vacation_novelty',
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('account_id', sa.String(length=26), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('units', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_aprobacion', sa.Date(), nullable=True),
    sa.Column('aprobado_por', sa.String(length=150), nullable=True),
    sa.Column('ledger_entry_id', sa.String(length=26), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('motivo_rechazo', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['vacation_account.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['vacation_ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacation_novelty', schema=None) as batch_op:
        batch_op.create_index('ix_vacation_novelty_account', ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacation_novelty_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_vacation_novelty_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('ix_vacation_novelty_empleado', ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacation_novelty_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacation_novelty_end_date'), ['end_date'], unique=False)
        batch_op.create_index('ix_vacation_novelty_estado', ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacation_novelty_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacation_novelty_start_date'), ['start_date'], unique=False)

    op.create_table('nomina_novedad',
    sa.Column('nomina_id', sa.String(length=26), nullable=False),
    sa.Column('empleado_id', sa.String(length=26), nullable=False),
    sa.Column('tipo_valor', sa.String(length=20), nullable=True),
    sa.Column('codigo_concepto', sa.String(length=50), nullable=False),
    sa.Column('valor_cantidad', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_novedad', sa.Date(), nullable=True),
    sa.Column('percepcion_id', sa.String(length=26), nullable=True),
    sa.Column('deduccion_id', sa.String(length=26), nullable=True),
    sa.Column('es_descanso_vacaciones', sa.Boolean(), nullable=False),
    sa.Column('vacation_novelty_id', sa.String(length=26), nullable=True),
    sa.Column('fecha_inicio_descanso', sa.Date(), nullable=True),
    sa.Column('fecha_fin_descanso', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['deduccion_id'], ['deduccion.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['nomina_id'], ['nomina.id'], ),
    sa.ForeignKeyConstraint(['percepcion_id'], ['percepcion.id'], ),
    sa.ForeignKeyConstraint(['vacation_novelty_id'], ['vacation_novelty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nomina_novedad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nomina_novedad_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nomina_novedad_vacation_novelty_id'), ['vacation_novelty_id'], unique=False)

    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liquidacion_concepto_id'), ['concepto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidacion_empleado_id'), ['empleado_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liquidacion_empleado_id'))
        batch_op.drop_index(batch_op.f('ix_liquidacion_concepto_id'))

    with op.batch_alter_table('nomina_novedad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nomina_novedad_vacation_novelty_id'))
        batch_op.drop_index(batch_op.f('ix_nomina_novedad_id'))

    op.drop_table('nomina_novedad')
    with op.batch_alter_table('vacation_novelty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacation_novelty_start_date'))
        batch_op.drop_index(batch_op.f('ix_vacation_novelty_id'))
        batch_op.drop_index('ix_vacation_novelty_estado')
        batch_op.drop_index(batch_op.f('ix_vacation_novelty_end_date'))
        batch_op.drop_index(batch_op.f('ix_vacation_novelty_empleado_id'))
        batch_op.drop_index('ix_vacation_novelty_empleado')
        batch_op.drop_index('ix_vacation_novelty_dates')
        batch_op.drop_index(batch_op.f('ix_vacation_novelty_account_id'))
        batch_op.drop_index('ix_vacation_novelty_account')

    op.drop_table('vacation_novelty')
    with op.batch_alter_table('vacation_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_vacation_ledger_type')
        batch_op.drop_index(batch_op.f('ix_vacation_ledger_id'))
        batch_op.drop_index('ix_vacation_ledger_fecha')
        batch_op.drop_index('ix_vacation_ledger_empleado')
        batch_op.drop_index('ix_vacation_ledger_account')

    op.drop_table('vacation_ledger')
    with op.batch_alter_table('nomina_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nomina_detalle_id'))

    op.drop_table('nomina_detalle')
    with op.batch_alter_table('comprobante_contable_linea', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comprobante_contable_linea_tipo_debito_credito'))
        batch_op.drop_index(batch_op.f('ix_comprobante_contable_linea_tipo_concepto'))
        batch_op.drop_index(batch_op.f('ix_comprobante_contable_linea_orden'))
        batch_op.drop_index(batch_op.f('ix_comprobante_contable_linea_nomina_empleado_id'))
        batch_op.drop_index(batch_op.f('ix_comprobante_contable_linea_id'))
        batch_op.drop_index(batch_op.f('ix_comprobante_contable_linea_empleado_id'))
        batch_op.drop_index(batch_op.f('ix_comprobante_contable_linea_empleado_codigo'))
        batch_op.drop_index(batch_op.f('ix_comprobante_contable_linea_concepto_codigo'))
        batch_op.drop_index(batch_op.f('ix_comprobante_contable_linea_comprobante_id'))
        batch_op.drop_index(batch_op.f('ix_comprobante_contable_linea_codigo_cuenta'))
        batch_op.drop_index(batch_op.f('ix_comprobante_contable_linea_centro_costos'))

    op.drop_table('comprobante_contable_linea')
    with op.batch_alter_table('vacation_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacation_account_policy_id'))
        batch_op.drop_index('ix_vacation_account_policy')
        batch_op.drop_index(batch_op.f('ix_vacation_account_id'))
        batch_op.drop_index(batch_op.f('ix_vacation_account_empleado_id'))
        batch_op.drop_index('ix_vacation_account_empleado')

    op.drop_table('vacation_account')
    with op.batch_alter_table('prestacion_acumulada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prestacion_acumulada_tipo_transaccion'))
        batch_op.drop_index(batch_op.f('ix_prestacion_acumulada_prestacion_id'))
        batch_op.drop_index(batch_op.f('ix_prestacion_acumulada_id'))
        batch_op.drop_index(batch_op.f('ix_prestacion_acumulada_fecha_transaccion'))
        batch_op.drop_index(batch_op.f('ix_prestacion_acumulada_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_prestacion_acumulada_empleado_id'))
        batch_op.drop_index(batch_op.f('ix_prestacion_acumulada_anio'))
        batch_op.drop_index('ix_prestacion_acum_periodo')
        batch_op.drop_index('ix_prestacion_acum_fecha')
        batch_op.drop_index('ix_prestacion_acum_empleado_prestacion')

    op.drop_table('prestacion_acumulada')
    with op.batch_alter_table('nomina_empleado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nomina_empleado_id'))

    op.drop_table('nomina_empleado')
    with op.batch_alter_table('nomina_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nomina_audit_log_usuario'))
        batch_op.drop_index(batch_op.f('ix_nomina_audit_log_id'))
        batch_op.drop_index(batch_op.f('ix_nomina_audit_log_accion'))

    op.drop_table('nomina_audit_log')
    with op.batch_alter_table('liquidacion_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liquidacion_detalle_liquidacion_id'))
        batch_op.drop_index(batch_op.f('ix_liquidacion_detalle_id'))

    op.drop_table('liquidacion_detalle')
    with op.batch_alter_table('interes_adelanto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interes_adelanto_id'))
        batch_op.drop_index(batch_op.f('ix_interes_adelanto_adelanto_id'))

    op.drop_table('interes_adelanto')
    with op.batch_alter_table('comprobante_contable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comprobante_contable_id'))

    op.drop_table('comprobante_contable')
    with op.batch_alter_table('adelanto_abono', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adelanto_abono_id'))
        batch_op.drop_index(batch_op.f('ix_adelanto_abono_adelanto_id'))

    op.drop_table('adelanto_abono')
    with op.batch_alter_table('vacation_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacation_policy_planilla_id'))
        batch_op.drop_index('ix_vacation_policy_planilla')
        batch_op.drop_index(batch_op.f('ix_vacation_policy_id'))
        batch_op.drop_index(batch_op.f('ix_vacation_policy_empresa_id'))
        batch_op.drop_index('ix_vacation_policy_empresa')
        batch_op.drop_index(batch_op.f('ix_vacation_policy_codigo'))

    op.drop_table('vacation_policy')
    with op.batch_alter_table('vacacion_empleado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacacion_empleado_id'))
        batch_op.drop_index(batch_op.f('ix_vacacion_empleado_empleado_id'))

    op.drop_table('vacacion_empleado')
    with op.batch_alter_table('vacacion_descansada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacacion_descansada_id'))
        batch_op.drop_index(batch_op.f('ix_vacacion_descansada_empleado_id'))

    op.drop_table('vacacion_descansada')
    with op.batch_alter_table('regla_calculo_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regla_calculo_audit_log_usuario'))
        batch_op.drop_index(batch_op.f('ix_regla_calculo_audit_log_id'))
        batch_op.drop_index(batch_op.f('ix_regla_calculo_audit_log_accion'))

    op.drop_table('regla_calculo_audit_log')
    with op.batch_alter_table('planilla_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planilla_audit_log_usuario'))
        batch_op.drop_index(batch_op.f('ix_planilla_audit_log_id'))
        batch_op.drop_index(batch_op.f('ix_planilla_audit_log_accion'))

    op.drop_table('planilla_audit_log')
    with op.batch_alter_table('historial_salario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_salario_id'))
        batch_op.drop_index(batch_op.f('ix_historial_salario_fecha_efectiva'))
        batch_op.drop_index(batch_op.f('ix_historial_salario_empleado_id'))

    op.drop_table('historial_salario')
    with op.batch_alter_table('carga_inicial_prestacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carga_inicial_prestacion_prestacion_id'))
        batch_op.drop_index(batch_op.f('ix_carga_inicial_prestacion_id'))
        batch_op.drop_index(batch_op.f('ix_carga_inicial_prestacion_empleado_id'))

    op.drop_table('carga_inicial_prestacion')
    with op.batch_alter_table('adelanto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adelanto_id'))
        batch_op.drop_index(batch_op.f('ix_adelanto_empleado_id'))

    op.drop_table('adelanto')
    with op.batch_alter_table('acumulado_anual', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acumulado_anual_tipo_planilla_id'))
        batch_op.drop_index(batch_op.f('ix_acumulado_anual_periodo_fiscal_inicio'))
        batch_op.drop_index(batch_op.f('ix_acumulado_anual_id'))
        batch_op.drop_index(batch_op.f('ix_acumulado_anual_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_acumulado_anual_empleado_id'))

    op.drop_table('acumulado_anual')
    # ### end Alembic commands ###
